### ISSUE TITLE
Length of packet (readcounter)

### ISSUE THREAD

**Issue by corradobr** [HWHardsoft/COVID19-Tracker-Arduino-MKR#1]
**original** 
if (readcounter < 255 ) {
                readcounter++;
 } 
**to read also the 'recovered' field for some countries** 
if (readcounter < **300** ) {
                readcounter++;
 }

**Comment by HWHardsoft** [comment]
Yes thanks for this advice. I've changed and tested the source code, according your suggestion.

**Comment by corradobr** [comment]
Thanks
