### ISSUE TITLE
Some countries not supported 

### ISSUE THREAD

**Issue by corradobr** [HWHardsoft/COVID19-Tracker-Arduino-MKR#2]
for some countries ie **United States** and **United Kingdom** 
the request:
err = http.responseStatusCode() ;
gives **err = 302**

**Comment by HWHardsoft** [comment]
Please use exactely the name of the worldometers.info side:
US for USA 
UK for United Kingdom

**Comment by corradobr** [comment]
Yes you are right , indeed    **us** for USA and **uk** for United Kingdom
